//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colegio
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante
    {
        public int id { get; set; }
        public string numeroIdentificacion { get; set; }
        public string nombreApellido { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string direcion { get; set; }
        public string telefono { get; set; }
    }
}
